### ISSUE TITLE
Replace local keyword with typeset -l

### ISSUE THREAD

**Issue by siteshwar** [rocky/kshdb#5]
`local` keyword is available only when ksh is compiled with bash emulation mode. We have disabled it in upstream through https://github.com/att/ast/pull/611, so use `typeset -l` instead of `local` in your scripts.

**Comment by rocky** [comment]
Think I got them all in dfe522b , but double check and reopen if I've missed something. Thanks.

**Comment by rocky** [comment]
One other thing I should mention. The reason I have typically favored `local` over `typeset -l` is because zsh uses `typeset -l` to mean something else, and both bash and zsh support `local`, even though that's not POSIX.
